package com.nhancv.sample.model;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by nhancao on 4/11/17.
 */

public class User extends RealmObject {

    @PrimaryKey
    private int id;
    private String name;
    private int age;
    private RealmList<Person> personList;

    // Standard getters & setters generated by your IDE…
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public RealmList<Person> getPersonList() {
        return personList;
    }

    public void setPersonList(RealmList<Person> personList) {
        this.personList = personList;
    }

    @Override
    public String toString() {
        return "User{" +
               "name='" + name + '\'' +
               ", age=" + age +
               '}';
    }
}
