package com.nhancv.sample.model;

import io.realm.RealmObject;

/**
 * Created by nhancao on 4/11/17.
 */

public class User extends RealmObject {

    private String name;
    private int age;

    // Standard getters & setters generated by your IDE…
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    @Override
    public String toString() {
        return "User{" +
                "name='" + name + '\'' +
                ", age=" + age +
                '}';
    }
}
